server:
  port: 8080
  basePath: /api
database:
  url: root:qwer1234@tcp(127.0.0.1:3306)/blog?parseTime=true&loc=Local&charset=utf8mb4
  maxIdle: 5
  maxOpen: 10
users:
  - username: admin
    password: '!1@2#3$4'
  - username: visitor
    password: '123456'
